### PR TITLE
Find data generator

### PR DESCRIPTION
**Pull request by EthanMarx**
- Adds `find_data` generator that asynchronously queries or loads specified segments of data and yields them. Data can either be queried using `TimeSeriesDict.get` , or read from h5 files if `data_dir` is specified.
- Adds `io` library for standardizing reading and writing timeseries to h5 files. h5 files have datasets that correspond to different `channels`, and `t0` and `sample_rate` attributes for reconstructing the sample times.

TODO: 
- [ ] Write tests for `find_data` generator
- [x] Write tests for `io` module

### CODE REVIEW

**Comment by EthanMarx** [comment]
(re)-implemented`read_timeseries` and `write_timeseries` in the `io.py` file.

- `write_timeseries` will write multiple channels to an h5 format with file name convention `{prefix}-{t0}-{length}.hdf5`. Currently, this assumes all channels have the same `sample_rate`.  Is there a DeepClean use case where channels may have differing sample_rates? 

- `read_timeseries` is similar to the `read_timeseries` in BBHnet. This will take a list of channels and a file path (presumably created via `write_timeseries`) and read in the channels. This will return `Dict[channel_name, data], times_array`. Again, this assumes all channels have the same sample_rate.

- Should these be standard across DeepClean and BBHnet? Should, for example, writing BBHnet raw / integrated network outputs follow these same standards?

Questions in `find.py` which contains the `find` generator:
- How should the `MEMORY_LIMIT` be handled? Should this be a module constant, or user supplied argument.
- The memory calculation relies on knowledge of the `sample_rate` of channels, which (at least for auxiliary channels) is typically unknown beforehand and different for every channel.  


How do the `Segment` and `TimeSlide` objects fit, if at all, into this library?

**Comment by mcoughlin** [comment]
@EthanMarx I think we want to be able to take in witness sensors of various sample_rates, but that is taken care of by interpolation. Is that what you mean? I definitely like the idea of BBHNet and DeepClean having the same standards, but up to you all.

**Comment by alecgunny** [comment]
Couple thoughts off the top of my head:
- I'm not sure we need the `parallelize` stuff in here. The main reason I made it in BBHNet was because I was being super lazy about how I was submitting jobs (i.e. submit them all up front and let them get iterated through as fast as they can), so if an error happened in the main process I didn't want to have to wait for all the jobs to finish before the script exited. Here we're being more judicious about how we're doing things, so we're probably fine to use the `concurrent.futures.ProcessPool` class as-is. The only extra thing I have in there is the threaded dictionary iteration, but doesn't look like we need that (at least for now).
- The `io` library assumes integer timestamps. I think this is fine since we're recording the actual `t0` and `duration` in the hdf5 archive and is consistent with [LIGO conventions](https://dcc.ligo.org/public/0026/T010150/000/T010150-00.pdf). We just need to make sure in `write_timeseries` that we're intify-ing everything in the filename so that it can be parsed later. I can foresee some benefit to having the filename timestamp exactly match the actual timestamp, e.g. you can tell from reading a file's name whether it will contain a timestamp without having to read any actual data, but the cases missed by this will be marginal and it's probably worth it for the sake of consistency.
- It looks like gwpy `TimeSeries` objects support reading/writing from `hdf5` natively. Basically they just associate the attributes `['dx', 'name', 'unit', 'x0', 'xunit']` with the `attrs` property on each channel's `dataset`. This is probably something I should have looked into way earlier, but given this maybe it makes sense to adopt this and let the `TimeSeries` and `TimeSeriesDict` objects handle the actual read/write inside the `io` library functions, and have the functions themselves primarily tackle file naming/searching conventions and eventually `TimeSlide` directory structure (which we probably don't need in this initial PR until we have a better sense of what this library will be). We can even modularize the naming conventions into functions so that people who want to do I/O with the objects themselves for more complex behavior can still follow the same conventions. So _our_ `write` function is meant basically syntactic sugar for people who already have arrays with the same sample rate and don't feel like wrapping them up into `TimeSeriesDict` and then writing, but those who want something more custom can just call `TimeSeriesDict.write`. Similarly, people can call our `read` function with a specified sample rate to get a nice clean rectangular tensor with the channels in the specified order and all sampled at the specified rate, but people who want something more complex can call `TimeSeriesDict.read` themselves.

**Comment by EthanMarx** [comment]
Thanks for the feedback! 

Yeah definitely agree parallelize is unnecessary, initially copied it over out of convenience.

Let me see If I understand you correctly: 

our `write` function will essentially be a thin wrapper around `TimeSeriesDict.write` that will package up `**datasets` (numpy arrays) of the same `sample_rate` into a TimeSeriesDict and write to a file with file name `"{prefix}-{t0}-{length}"`

```
def write_timeseries(
   t0: float,
   prefix: str,
   sample_rate: float,
   **datasets
)
# package up datasets into TimeSeriesDict
TimeSeriesDict.write("{prefix}-{t0}-{length}")
```

Analogously, our `read` function is a thin wrapper around `TimeSeriesDict.read` that will parse the `TimeSeriesDict` into nice arrays.

```
def read_timeseries(
   path: Path
   *datasets
):

    ts_dict = TimeSeriesDict.read(path)
    
    # downselect to requested datasets,
    # perform checks to ensure same sample rates, etc.
   
    # return requested data in nice arrays
    return ts_dict.values()

```

This all makes total. sense to me. This ensures that our read and writes are directly compatible with `gwpy`'s. These functions may seem like overkill, but without these utilities I imagine we'll be doing the same checks, and conversions to arrays over and over.

**Comment by alecgunny** [comment]
@EthanMarx exactly, just providing people with multiple levels of abstraction so they can pick the one that makes the most sense for their use case.

**Pull request merged**
